version: '3.4'

services:
  web:
    image: luttrellapp
    build:
      context: ./services/web/
      dockerfile: ./Dockerfile
    command: /home/microblog/venv/bin/gunicorn --bind 0.0.0.0:8000  microblog:app
    depends_on:
      - mysql
    env_file:
      - ./services/web/.env
    expose:
      - "8000"
  nginx:
    build:
      context: ./services/nginx/
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/app/static
    ports:
      - "1337:80"
      - "443:443"
    depends_on:
      - web
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "microblog"
      MYSQL_USER: "microblog"
      MYSQL_PASSWORD: "<database-password>"

volumes: 
  mysql-data:
  static_volume: